apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
        - name: employee-app
          image: rakshitsuman/employee-image-latest:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/employeedepdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
---
apiVersion: v1
kind: Service
metadata:
  name: employee-service
spec:
  type: LoadBalancer   # public access (EKS/GKE/AKS etc.)
  selector:
    app: employee-app
  ports:
    - port: 80        # external port
      targetPort: 8080   # container port
